# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.1.14.dev22+g453dc0f.d20220601'
version_tuple = (0, 1, 14, 'dev22', 'g453dc0f.d20220601')
